<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Minecraft\minecraft\1.21.8\1.21.8.jar">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Minecraft\minecraft\1.21.8\1.21.8.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Minecraft\minecraft\1.21.8\1.21.8-natives\stand.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Minecraft\minecraft\1.21.8\saves\stand.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Minecraft\minecraft\1.21.8\resourcepacks\stand.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Minecraft\VML\Script\26.1\NewFile1.txt">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\style\index.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\style\icon\minecraft.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\Config\usingHtml.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\style\Dark.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\style\Light.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Minecraft\.minecraft\a\" />
    <Folder Include="Minecraft\assets\" />
    <Folder Include="Minecraft\minecraft\" />
    <Folder Include="Minecraft\VML\Script\" />
    <Folder Include="Minecraft\VML\Style\" />
  </ItemGroup>

</Project>
